MODULE STRING_COMMONS
IMPLICIT NONE

INTEGER :: N_IMAGES, N_DOF, MAX_ITER, CLIMB_MAX_ITER, MAXSTEP, OUTPUTSTEP
DOUBLE PRECISION, ALLOCATABLE :: MIN_1(:), MIN_2(:), IMAGES(:,:), V(:), E_IMAGES(:), CLIM_IMAGE(:), CLIM_E, POS_IMAGES(:)
DOUBLE PRECISION, ALLOCATABLE :: STRING_ANGLES(:), T_SPEED, EIGEN_LENGTH, EIGEN_SPRING
DOUBLE PRECISION :: DT, PATH_LENGTH, CONVERGENCE, CLIMB_CONVERGENCE, CM1, CLIMB_DT, WEIGHT_EXP
DOUBLE PRECISION :: EIGEN_DIST, EIGEN_CONVERGENCE, EIGEN_MAX_ITER, EIGEN_DT
DOUBLE PRECISION, ALLOCATABLE :: EIGENVEC(:), MEP(:,:), MEP_DATA(:,:)
DOUBLE PRECISION :: EIGENVAL
INTEGER :: DOWN_SAVES
LOGICAL :: CLIMBSTAT, EIGENSTAT, DEBUG

END MODULE STRING_COMMONS
